### PR TITLE
Updating to version 1.2.1 of ScssPhp

### PR DESCRIPTION
**Pull request by shadoath**
A large update to the ScssPHP compiler to be sure. I want to push forward with this without hitting too many deprecations or large version bumps while getting as many fixes in as possible in this first update.

### [1.2.1](https://github.com/scssphp/scssphp/releases/tag/1.2.1)

- Fix @import url() parsing (@leonardfischer, @Cerdic)
- Fix various directive parsing issues (@zoglo, @CatoTH, @Cerdic)
- Fix min(), max() (@Cerdic)
- Fix str-length(), str-index(), and str-insert() (@Cerdic)
- Fix is-superselector() and other select issues (@Cerdic)
- Fix call() argument name (@Cerdic)
- Fix random() (@Cerdic)
- Fix list-separator() on empty or one element list (@Cerdic)

#### COMPAT BUSTERS:

- Cache: cache directory must exist and be writeable (robocoder)
- Deprecation warning when call() is used with a string (Cerdic)
- Compiler: deprecated throwError() (stof)
- Remove ignoreErrors mode (stof)
- Drop support for configuring precision (stof)
- bin/pscss deprecated --continue-on-error and --precision (stof)

**Sass compatibility:**

- Partial fix of special cases in hsl/hsla functions (Cerdic)
- In certain interpolations, the spec seems to prefer to force a double quote for output strings (Cerdic)
- Fix list separated values with no delimiter with a keyword between two strings (Cerdic)
- Fix spaces escaping in @import path strings (Cerdic)
- Fix single/double quote escaping in single/double scope strings (stof)
- Refactor handling of strings and escape sequences (stof)
- Fix the enclosedList parsing in a more generic way (Cerdic)
- Parser: explicitly flatten where expected (Cerdic)
- Color function can be called with a var(..) argument (Cerdic)
- Throw an error when passing too many arguments (stof, Cerdic)
- Don't coerce anything into a map but throw an error if it's not at all matching a map (Cerdic)
- In the @atroot (#{with: media}) the interpolation has to be reparsed in the compiler before trying to manipulate as a map (Cerdic)
- Throw an error if positional and named passed, even on a splat... argument, except if this is the only one (Cerdic)
- Fix map-remove() : second argument key can be a list of arguments (Cerdic)
- Fix parsing value list in function call made of value list of 1 element (Cerdic)
- Fix name of arguments on functions mix(color1,color2), map-merge(), comparable(), selector-extend(), selector-replace(), selector-parse() (Cerdic)
- Fix saturate(50%) (Cerdic)
- Throw an error if a value that should be in a range is not a numeric value (Cerdic)
- Add error handling for invalid type in some color functions (Cerdic)
- --& is a valid custom property (where & should be interpreted as self selector) (Cerdic)
- Replace self selector in target part before the pushExtends() (Cerdic)
- Add a proper error when trying to take a modulo by 0 (stof)
- Properly detect the wrong operands for for loops (stof)
- Fix the parsing of while(false) loop (stof)
- Introducing scss get-function() and T_FUNCTION_REFERENCE type (Cerdic)
- Reorder color names (stof)
- Change output order for nested selectors (stof)
- Simplify the handling of comments to be more spec-compliant (stof)
- Refactor the format of the output for debug and warn directives (stof)
- Discard comments in include arguments (stof)
- Fix parsing of id tokens in values (stof)
- Respect precision when computing alpha channel (stof)
- Fix keyframe parsing in css files (dwachss, Cerdic)
- In plain CSS, a property can only occur in a selector (ryssbowh, Cerdic)

**Bug Fixes:**

Compiler: fix undefined offset 2 (chrisblakley)

**New Features:**

- Compiler: add getSourcePosition() (ryssbowh, robocoder)
- ParserException: add sourcePosition getter/setter (cbl, robocoder)

**Testing:**

- Many, many sass-spec test improvements (stof, Cerdic)
- Update sass-spec tests (2020.08.20)

**Misc:**

- Add SassException interface (stof)
- Add polyfill for mb_chr (stof)
- Update to PSR-12 (robocoder)
- Add php 8 nightly to Travis CI (robocoder)

### [1.1.0](https://github.com/scssphp/scssphp/releases/tag/1.1.0)

- Fix extend and class concatenation (@develth, @Cerdic)
- Fix arguments selector issue (@stempora, @Cerdic)
- Fix regression when member units are not normalizable (@jszczypk, @Cerdic)
- Remove box.json.dist from .gitattributes (@reedy)
- 32-bit fixes for Base64VLQ, encode(), and unique-id() (@remicollet, @robocoder)
- Fix index of map within list of maps (@stempora, @robocoder)

### [1.1.0](https://github.com/scssphp/scssphp/releases/tag/1.1.0)
- Fix the handling of call traces for exceptions of native functions (@stof)
- Add named call stack entries for imports (@stof)
- Fix leaks in the call stack (@stof)
- Qualify function calls when the compiler can optimize them (@stof)
- Remove deprecated Parser::to() and Parser::show() methods (@robocoder)

### [1.0.9](https://github.com/scssphp/scssphp/releases/tag/1.0.9)

- Fix parsing issues around #, +, -, -- (@Cerdic)
- Fix @import compatibility (@Cerdic)
- Add vendor-prefixed scssphp-glob() function (@havutcuoglu, @robocoder)
- Remove PHP version and mbstring.func_overload checks (@KryukovDS, @robocoder)
- Fix multiple issues with Bootstrap 4.4.1 and master (@fuzegit, @Cerdic)
- Fix variables interpolation bug (@Seonic, @Cerdic)

### [1.0.8](https://github.com/scssphp/scssphp/releases/tag/1.0.8)

- Import of valid scss files fails silently (@oyejorge, @Cerdic)
- Undefined $libName (@enricobono, @robocoder)
- Fix division and modulo per sass-spec (@Cerdic)
- Fix expressions in at directives (@Cerdic)
- Introduce support for custom properties (@Cerdic)
- Function compatibility issues with functions (abs, ceil, floor, max, min, percentage, random, round), units, and conversions. (@Cerdic)

### [1.0.7](https://github.com/scssphp/scssphp/releases/tag/1.0.7)

- Fix problem with Bootstrap 4.4 / Responsive containers (@nvindice, @Cerdic)
- Fix issue with pseudoelement selectors order in @extend'ed elements (@CrazyManLabs, @Cerdic)
- example/Server.php moved to https://github.com/scssphp/server

### [1.0.6](https://github.com/scssphp/scssphp/releases/tag/1.0.6)

- Many sass-spec compatibility fixes (@Cerdic)
- Discriminate shorthands vs real divisions in border-radius property (@joakipe, @Cerdic)
- Base64VLQ - 32-bit overflow fixes from Closure implementation (@remicollet, @robocoder)
- Formatter for nested properties removes semicolon (@Mythos07, @Cerdic)
- Variables scope issues (@jducro, @Cerdic)
- Using @extend creates invalid output with nested classnames (@bmbrands, @Cerdic)
- Fixed sourceMapGenerator bug if semicolons are stripped. (@ugogon)

### [1.0.5](https://github.com/scssphp/scssphp/releases/tag/1.0.5)

**Compatibility and Bug Fixes:**

- interpolation fixes (@Cerdic)
- undefined sourceIndex (@connerbw, @robocoder)

**Maintenance:**

- phpunit test updates (@stof)
- using is_null(), is_dir(), is_file() for consistency (@robocoder)

### [1.0.4](https://github.com/scssphp/scssphp/releases/tag/1.0.4)

**Bug fixes / Compatibility:**

- border-radius shorthand support (@alex-shul, @Cerdic)
- allow zip() function to use all types as arguments (@devdot, @Cerdic)
- @each forcing unwanted type conversion (@devdot)
- rgb() and colour compatibility improvements (@Cerdic)
- str-splice broken in php 7.4

**Maintenance:**

- composer and travis configuration updates
- remove obsolete Base64VLQEncoder class

### [1.0.3](https://github.com/scssphp/scssphp/releases/tag/1.0.3)

**Compatibility fixes:**

- @at-root, @import, and url(//host/image.png) fixes (@Cerdic)
- join operator with interpolated values vs vars or static values (@julienmru, @Cerdic)
- Implemented passing Arguments to Content Blocks (@jensniedling, @Cerdic)
- Support whitespaces inside :not() (@schliesser)
- Compile non-roots comments also (@fabsn182, @Cerdic)

### CODE REVIEW

**Comment by stof** [comment]
1.2.1 is still several months old

**Comment by shadoath** [comment]
@stof true, my thought was to push up to this version and release an update. Then jump up again in the scssPHP version, thus giving more flexibility to which version someone might be locked into with this plugin.
As you are more familiar with the internals of the scssphp repo, do you see issues arising from making such a big jump from 1.0.2 to 1.5.2?

**Comment by stof** [comment]
Well, between 1.0.2 and 1.5.2, scssphp became more spec compliant, by fixing lots of issues. If your scss source code was invalid but accepted by scssphp, things might fail (but this is true for any release as we don't provide backward compatibility for our bugs). However, these changes also means that we fixed a bunch of issues that improve the compilation.
For the cases where we supported features that are not supported by dart-sass but that keeping them was not causing spec compliance issues elsewhere, we deprecated them and we will remove them only in 2.0, to warn users.

The 1.5.0 and 1.5.1 releases should be avoided though, as they broke compilation of Bootstrap (we fixed some spec compliance issue, which made the impact of another spec compliance issue a lot bigger than before).

Upgrading to 1.5 will also have an impact on the PHP API of scssphp, as we deprecated part of it in favor of a more modern API (the one we want for 2.0). But upgrading should be easy enough (and if you have an error handler supporting the Symfony convention for reporting deprecations through `@trigger_error(..., E_USER_DEPRECATED)`, you would get deprecation warnings for them as we follow that convention too).

**Comment by stof** [comment]
There is one impact though when upgrading to 1.5 though: it is now required to have either mbstring or iconv installed (or a polyfill for one of them)

**Comment by shadoath** [comment]
@stof Thank you for the important insights into the version and requirements of scssphp. I'm going to keep below 1.5 for now to avoid the need for mbstring or iconv (unless I find a simple way to include those). 
I'll merge this one in and then open another PR for to bring this repo up to 1.4.1

**Comment by stof** [comment]
@shadoath without mbstring or iconv, the behavior of the Sass compiler does not respect the Sass spec about how indexes work in strings. So even before 1.5, they are necessary for things to work properly.

**Comment by stof** [comment]
note that `symfony/polyfill-iconv` ships a userland implementation of iconv functions in case PHP was compiled without iconv (but this package is big, as it has to ship metadata about the whole Unicode).
In practice, as iconv is an extension enabled by default in PHP since at least PHP 5.3 (I haven't checked older versions, and I started doing serious work with PHP 5.3 so I never cared about it for older versions), scssphp decided that this requirement was fine.

**Comment by stof** [comment]
Btw, requiring mbstring does not look like a huge blocker to me. https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions lists mbstring as a recommended extension for wordpress anyway.

And btw Wordpress itself ships a polyfill for `mb_strlen` and `mb_substr`, so only `mb_strpos` is missing for what we need (we also use `mb_chr`, but the fallback for that one does not depend on `iconv`)

**Pull request merged**
