### PR TITLE
Add property defs to Wp_Scss class and update constructor phpdocs

### LINKED ISSUE #245: PHP 8.2 Creation of dynamic property ... is deprecated
A few deprecated messages

[12-May-2023 19:05:04 UTC] PHP Deprecated:  Creation of dynamic property Wp_Scss::$scss_dir is deprecated in /wp-scss/class/class-wp-scss.php on line 22
[12-May-2023 19:05:04 UTC] PHP Deprecated:  Creation of dynamic property Wp_Scss::$css_dir is deprecated in //wp-scss/class/class-wp-scss.php on line 23
[12-May-2023 19:05:04 UTC] PHP Deprecated:  Creation of dynamic property Wp_Scss::$compile_errors is deprecated in/wp-scss/class/class-wp-scss.php on line 24
[12-May-2023 19:05:04 UTC] PHP Deprecated:  Creation of dynamic property Wp_Scss::$scssc is deprecated in /plugins/wp-scss/class/class-wp-scss.php on line 25
[12-May-2023 19:05:04 UTC] PHP Deprecated:  Creation of dynamic property Wp_Scss::$cache is deprecated in /plugins/wp-scss/class/class-wp-scss.php on line 27
[12-May-2023 19:05:04 UTC] PHP Deprecated:  Creation of dynamic property Wp_Scss::$sourcemaps is deprecated in/plugins/wp-scss/class/class-wp-scss.php on line 32

It would be nixe, if you fix this. Thanks.

### PR DESCRIPTION
**Pull request by garrettw**
Closes #245

### CODE REVIEW

**Comment by Tusko** [comment]
pls check and update 8.2 compability

**Review by shadoath — APPROVED** [review]

**Comment by Hyperpolymath** [comment]
Hiya,

I hope this is the right place to post, and this image is going to show below:

image

If not, I will send the text of it after it's posted. 

I wonder if you know what I need to do to fix this, or if it is something your side. There is a comment thread that appears on the wordpress.org site that directs us here.

I am using PHP 8.3 with latest version of the plugin and Wordpress. The reporting read pit that I just shared is from the Query Monitor plug in, and if you need anything else, let me know.

**Comment by Hypaepa** [comment]
You need to rewrite the file : **class/wp-scss.php,** as :

`<?php
//Required to use get_home_path()
require_once(ABSPATH . 'wp-admin/includes/file.php');
include_once(WPSCSS_PLUGIN_DIR . '/scssphp/scss.inc.php');
use ScssPhp\ScssPhp\Compiler;

class Wp_Scss {
  private $scss_dir;
  private $css_dir;
  private $compile_errors;
  private $scssc;
  private $cache;
  private $sourcemaps;
  private $cache_file;

  /**
   * Set values for Wp_Scss::properties
   *
   * @param string scss_dir - path to source directory for scss files
   * @param string css_dir - path to output directory for css files
   * @param string compile_method - type of compile (compressed or expanded)
   *
   * @var object scssc - instantiate the compiling object.
   *
   * @var array compile_errors - catches errors from compile
   */
  public function __construct ($scss_dir, $css_dir, $compile_method, $sourcemaps) {

    $this->scss_dir         = $scss_dir;
    $this->css_dir          = $css_dir;
    $this->compile_errors   = array();
    $this->scssc            = new Compiler();

    $this->cache = WPSCSS_PLUGIN_DIR . '/cache/';

    $this->scssc->setOutputStyle( $compile_method );
    $this->scssc->setImportPaths( $this->scss_dir );

    $this->sourcemaps = $sourcemaps;
  }`

**Comment by shadoath** [comment]
@Hypaepa  can you open a PR?

**Pull request merged**
