### PR TITLE
Fix import files not triggering compilation

### PR DESCRIPTION
**Pull request by johntbb**

### CODE REVIEW

**Comment by andreyc0d3r** [comment]
This won't work on windows machines

**Comment by andreyc0d3r** [comment]
The problem still persists on windows. `FilesystemIterator::SKIP_DOTS` helps but not sure about repercussions on *nix machines.

**Comment by johntbb** [comment]
> Can you please explain why did you propose to replace `RecursiveDirectoryIterator` with `FilesystemIterator`?

I think you're confused. The original source code was using `FilesystemIterator`. I altered the code to correctly use `RecursiveDirectoryIterator`.

I hope this helped out. Many Thanks.

**Comment by shadoath** [comment]
Looking into this both `FilesystemIterator::SKIP_DOTS` and `RecursiveDirectoryIterator::SKIP_DOTS` pass the same code of **4096**. 
So it appears the main change is passing SKIP_DOTS to the `RecursiveDirectoryIterator` instead of the `RecursiveIteratorIterator` which makes sense as the RecursiveIteratorIterator does not take an argument for SKIP_DOTS. So this PR would be limiting the (S)CSS checks to only files within the defined (S)CSS folders. 
@richrd I would expect this to be the case instead of checking the entire WP tree for any SCSS file changes (although that is how it looks to work now...)

**Comment by shadoath** [comment]
Out of date. If you want these changes please fix merge conflicts or create new PR.

**Pull request closed without merging**
