### PR TITLE
Revert "Updates scssphp to 0.6.3"

### PR DESCRIPTION
**Pull request by brrn**
Reverts ConnectThink/WP-SCSS#52

### CODE REVIEW

**Comment by brrn** [comment]
Please test this update. I updated the plugin on a local test site, and after changing a line of scss, the front end would not render until I re-saved the WP-SCSS settings in WordPress.

**Comment by MarcGuay** [comment]
After updating I experienced the following errors:

```
Sass Compiling Error

/public_html/wp-content/plugins/wp-scs/cache/ 
"File Permission Error, permission denied. Please make the cache directory writable."
```

The directory did not contain a cache dir so I created it, and after that I received the following error:

```
 PHP Fatal error:  Class 'scss_formatter_compressed' not found in /public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 188, referer: http://...
```

Which seems related to the changes to admin options that require re-saving.  I would suggest breaking up the SCSS parser changes from the options changes if possible.  Perhaps I'll take a stab at it...

**Comment by leepeterson** [comment]
@MarcGuay Any luck with this update? It's desperately needed :)

**Comment by MarcGuay** [comment]
@leepeterson Hi Lee.  If I'm not mistaken an update to 0.6.3 has been put in the main branch.

**Pull request closed without merging**
